version: "3.7"
services:
  app:
    build:
      args:
        user: dolly
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: easybill
    container_name: easybill-app
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - 6001:6001
    volumes:
      - ./:/var/www
    networks:
      - easybill

  nginx:
    image: nginx:alpine
    container_name: easybill-nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - easybill

  postgres:
    container_name: easybill-postgres
    image: postgres:latest
    environment:
      POSTGRES_PORT: 5442
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5442:5432
    volumes:
        - postgres_data:/var/lib/postgresql/data
    networks:
      - easybill

volumes:
    postgres_data:
networks:
  easybill:
    driver: bridge